### ISSUE TITLE
Very strange usage

### ISSUE THREAD

**Issue by LinusU** [jonschlinkert/pad-left#1]
This library always appends a static number of characters in front of the string. I think that the expected behaviour is to pad the string so that it's always at least a specific length.

This is how every other string padding library works.

Current behaviour:

``` javascript
padLeft(  '4', 4, '0') // 00004
padLeft( '35', 4, '0') // 000035
padLeft('459', 4, '0') // 0000459
```

Sane behaviour:

``` javascript
padLeft(  '4', 4, '0') // 0004
padLeft( '35', 4, '0') // 0035
padLeft('459', 4, '0') // 0459
```

**Comment by jonschlinkert** [comment]
Thanks for the pr, makes sense.

**Comment by LinusU** [comment]
Super, thanks!
