### ISSUE TITLE
To fulfill both backward-compatibility and improvement for modern engines.

### ISSUE THREAD

**Issue by ghost** [jonschlinkert/pad-left#11]
_ES6_ has evolved a lot so far; now it has `String.prototype.padStart` and `String.prototype.repeat`.
However, `pad-left` is still a great module for backward-compatibility.
But since it does not use the built-in methods, modern engines may not perform their best when they run this module.
So my proposal is to let them use what they know.

To fulfill both backward-compatibility and improvement for modern engines, it could be modified like below.
In this modification, I did not make any slowdown in the function code but in the module initialization.
i.e. I did not put the `if`-`else` thing in the `padLeft` function body.

### Original
```javascript
'use strict';

var repeat = require('repeat-string');

module.exports = function padLeft(str, num, ch) {
  str = str.toString();

  if (typeof num === 'undefined') {
    return str;
  }

  if (ch === 0) {
    ch = '0';
  } else if (ch) {
    ch = ch.toString();
  } else {
    ch = ' ';
  }

  return repeat(ch, num - str.length) + str;
};
```

### Modified
```javascript
'use strict';

if("padStart" in String.prototype)
{
  module.exports = function padLeft(str, num, ch) {
    return str.toString().padStart(num, ch);
  };
}
else if("repeat" in String.prototype)
{ // Engines support `repeat` may not support `padStart`, according to http://node.green.
  module.exports = function padLeft(str, num, ch) {
    str = str.toString();

    if (typeof num === 'undefined') {
      return str;
    }

    if (ch === 0) {
      ch = '0';
    } else if (ch) {
      ch = ch.toString();
    } else {
      ch = ' ';
    }

    return ch.repeat(num - str.length) + str;
    // To avoid an extra function call, I did not wrap `String.prototype.repeat` but use it directly.
  };
}
else
{
  var repeat = require('repeat-string');
  module.exports = function padLeft(str, num, ch) {
    str = str.toString();

    if (typeof num === 'undefined') {
      return str;
    }

    if (ch === 0) {
      ch = '0';
    } else if (ch) {
      ch = ch.toString();
    } else {
      ch = ' ';
    }

    return repeat(ch, num - str.length) + str;
  };
}
```

----------

To check the method support, I used `in` operator, based on the result from https://perf.zone.

![image](https://user-images.githubusercontent.com/15066073/31578175-c7f8bde0-b156-11e7-8bfe-a7bc31a10e7d.png)

----------

I was wondering if you could let me _Pull-request_ this one. Thank you.

**Comment by jonschlinkert** [comment]
> But since it does not use the built-in methods, modern engines may not perform their best when they run this module.

As the benchmarks on the readme show, this library is much faster than the native implementation. , I've also run the benchmarks on several versions of node.js, and chrome, and this implementation is always faster. 

That said, given that the results of your own benchmarks were so close, I see no value in complication the code as much as you're proposing with your PR. If you can get closer to 20m ops/sec or higher, please feel free to create another PR to discuss. Thanks
