### ISSUE TITLE
Version 0.0.3 on npm.

### ISSUE THREAD

**Issue by skyfarliu** [jonschlinkert/pad-left#5]
Hi, 

One of my dependencies requires version 0.0.3 on npm. Is it removed?

I am getting the following error when running `npm i`

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3

npm ERR! No compatible version found: left-pad@0.0.3
npm ERR! Valid install targets:
npm ERR! 0.0.9
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

**Comment by jonschlinkert** [comment]
wrong repo, that says `left-pad`, this is `pad-left`. fwiw this lib is orders of magnitude faster than left-pad because of https://www.npmjs.com/package/repeat-string

**Comment by skyfarliu** [comment]
Indeed. My apology. https://github.com/azer/left-pad/issues/5
