### ISSUE TITLE
Missing mocha from dev-dependencies

### ISSUE THREAD

**Issue by parro-it** [jonschlinkert/pad-left#6]
Travis test are failing

**Comment by jonschlinkert** [comment]
I'm such an airhead sometimes. I updated the module earlier because i specifically wanted to add mocha lol. sometimes I go to the grocery for one thing, and come home with 10 things and not what I went for...

thanks for the heads up.

**Comment by parro-it** [comment]
:smile: no worries, it happens!

**Comment by jonschlinkert** [comment]
yeah, a lot if you ask my wife lol

**Comment by parro-it** [comment]
I sometime [delete my repos](https://github.com/parro-it/awesome-micro-npm-packages/issues/1) by mistake!

**Comment by jonschlinkert** [comment]
lol, yeah that sucks. looks like you've recovered nicely though!

**Comment by parro-it** [comment]
That's because I'm lucky... I retrieved a version of the page from chrome cache!

**Comment by jonschlinkert** [comment]
nice! I wouldn't have thought of that
