### ISSUE TITLE
Update the benchmarks

### ISSUE THREAD

**Issue by benjamingr** [jonschlinkert/pad-left#7]
Hey, I just noticed this package, care to update the benchmarks to run against the latest left-pad?

**Comment by jonschlinkert** [comment]
huh, yeah it looks like they updated the code to use the same pattern as this lib (from repeat-string).  Should I steal their optimizations first without attribution? Or just run benchmarks as is? jk but it unfortunately seems like this is becoming the norm.

**Comment by jonschlinkert** [comment]
removed my previous comment. I misread your question on my phone and thought you said left-pad was "updated", and [this one ](https://github.com/stevemao/left-pad/blob/master/index.js) was the only one I saw that was just updated. (and it's using something similar to my code).

anyway, sure, I can update the benchmarks

**Comment by benjamingr** [comment]
Yeah, that one.

**Comment by jonschlinkert** [comment]
Sorry for the delay. [benchmarks](https://github.com/jonschlinkert/pad-left#benchmarks). The benchmarks show both left-pad libs, the one on npm and the stevemao one.

@benjamingr what is the reasoning behind making the code in stevemao/left-pad more like the code in this one, versus just using this lib?

**Comment by benjamingr** [comment]
I didn't know this lib, I just used the code from V8 and caching which was simple - I only googled for other libraries later to look for benchmarks.

**Comment by jonschlinkert** [comment]
k, closing since benchmarks were updated
